### ISSUE TITLE
question: op.html

### ISSUE THREAD

**Issue by RafaelKoch** [MicrosoftDocs/nav-content#37]
Hi,
I just tried to build with docfx. In `docfx.json` there is a reference to `op.html` as a template which is not there apparently. So building fails with a warning. If I remove this from the config docfx will build _something_ but every html then consists only of a toc with broken links.

I am pretty new to this, so I am probably missing out on something stupid. Some hint would be appreciated. Many thanks!

**Comment by RafaelKoch** [comment]
okay, did some more reading and got the very basics of templating in docfx. Using the template `statictoc` at least gives me a basically functional output. Pretty ugly though.... Can You share op.html?

**Comment by edupont04** [comment]
Hi there,
Sorry for the delay in getting back to you on this! op.html is indeed a template that is specified in the docfx.json. However, as mentioned in our readme.md, we recommend that you use the NAVdocfx.json file to configure the build command - there, we have added a Help Server-specific template that makes the right HMTL files for Help Server. You can see NAVdocfx.json in the dynamics-nav-app folder, and the template for Help Server is in the https://github.com/MicrosoftDocs/nav-content/tree/live/Templates/HelpServer folder.

I hope this answers your question. Otherwise, feel free to reactivate the issue.
