### ISSUE TITLE
help for Reverse Charge VAT is not very helpful

### ISSUE THREAD

**Issue by dirkree** [MicrosoftDocs/nav-content#57]
This documentation isn’t very helpful.  If doesn’t explain what you are supposed to enter in the fields.
For example on Sales & Receivables Setup you have the following fields:
Reverse Charge VAT Posting Gr.,  Domestic Customers,  Invoice Wording

The help file says:
.. fill in the fields as necessary. 

It doesn’t explain what you need to fill the fields in with.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4c0bc97-25b9-1455-5203-63f58387474d
* Version Independent ID: eaf61baf-d54a-5b64-f5ce-d1c872ed606e
* Content: [How to Set Up Reverse Charges on VAT - Dynamics NAV App](https://docs.microsoft.com/en-us/dynamics-nav-app/localfunctionality/unitedkingdom/how-to-set-up-reverse-charges-on-vat)
* Content Source: [dynamics-nav-app/LocalFunctionality/UnitedKingdom/how-to-set-up-reverse-charges-on-vat.md](https://github.com/MicrosoftDocs/nav-content/blob/live/dynamics-nav-app/LocalFunctionality/UnitedKingdom/how-to-set-up-reverse-charges-on-vat.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! You are right that the article does not describe the individual fields or the values to enter in them. This is by design because we believe the product itself should help you understand that through embedded user assistance.

Depending on how you use Dynamics NAV, you will have access to a tooltip for each field. This is expected to explain the field and the data it holds.

I hope this answers your question. Otherwise, please let me know. I'm keeping the issue open for now.

**Comment by dirkree** [comment]
Hi Eva,
In the last 7 days we received two news requests from partners who did not understand these locally required fields and how these fields are related to "normal" EU Reverse Charge businesses which are controlled in the VAT Posting Setup

**Comment by edupont04** [comment]
Assigning to the PM who owns this. My name displays as the content owner for historical reasons, but this is not longer owned by me.
